### ISSUE TITLE
Unit tests for driver.driver

### ISSUE THREAD

**Issue by zthh626** [UVic-Environmental-Engineering-Club/usv-pi#1]
add_gps_coord(route: List[GpsCoord], coord: GpsCoord) -> List[GpsCoord]
- Takes a GpsCoord and add it to the list, then returns it back

remove_gps_coord(route: List[GpsCoord], coord: GpsCoord) -> List[GpsCoord]
- Removes a GpsCoord from the list, then returns it back

reset_route() -> List[GpsCoord]
- Simply returns empty list

start_route(route: List[GpsCoord], start_target: GpsCoord) -> Process
- Not implemented yet, it's ok for this one to fail

def pause_route(route: List[GpsCoord]) -> GpsCoord
- Not implemented yet, it's ok for this one to fail

**Comment by johnmck95** [comment]
All but start_route() and pause_route() have been completed and merged. To be completed once their functionality is finalized.

**Comment by zthh626** [comment]
Closing this as the rest of the work needs to be specced out with the driving algo
